/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketotomasyonu;

import java.util.List;
import javax.swing.JFrame;
import marketotomasyonu.Database.Database;
import marketotomasyonu.Modeller.Musteri;
import marketotomasyonu.Modeller.Personel;

/**
 *
 * @author lenovo
 */
public class PersonelIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form PersonelIslemleri
     */
    JFrame frame;
    List<Personel> personelListe;
    public PersonelIslemleri(JFrame frame) {
        initComponents();
        this.frame = frame;
        personelListe = Database.personelleriGetir();
        personelList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return personelListe.size();}
            public String getElementAt(int i) { return personelListe.get(i).toString(); }
        });
    }
    public PersonelIslemleri() {
        initComponents();
        personelListe = Database.personelleriGetir();
        personelList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return personelListe.size();}
            public String getElementAt(int i) { return personelListe.get(i).toString(); }
        });
    }
    public void personelSil(){
        Personel personel = personelListe.get(personelList.getSelectedIndex());
        Database.personelSil(personel);
    }
    public void listeGuncelle(){
            personelListe = Database.personelleriGetir();
            personelList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return personelListe.size();}
            public String getElementAt(int i) { return personelListe.get(i).toString(); }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFArama = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        personelList = new javax.swing.JList<>();
        buttonPersonelEkle = new javax.swing.JButton();
        buttonPersonelSil = new javax.swing.JButton();
        buttonPersonelDuzenle = new javax.swing.JButton();
        buttonAra = new javax.swing.JButton();
        buttonCikisYap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 357));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 357));

        jLabel1.setText("Personel Ara");

        jScrollPane3.setViewportView(personelList);

        buttonPersonelEkle.setText("Personel Ekle");
        buttonPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonelEkleActionPerformed(evt);
            }
        });

        buttonPersonelSil.setText("Personel Sil");
        buttonPersonelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonelSilActionPerformed(evt);
            }
        });

        buttonPersonelDuzenle.setText("Personel Düzenle");
        buttonPersonelDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonelDuzenleActionPerformed(evt);
            }
        });

        buttonAra.setText("jButton4");
        buttonAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAraActionPerformed(evt);
            }
        });

        buttonCikisYap.setText("Geri");
        buttonCikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCikisYapActionPerformed(evt);
            }
        });

        jLabel2.setText("TC No:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFArama, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPersonelSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPersonelDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(buttonPersonelEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(buttonCikisYap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCikisYap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAra))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPersonelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPersonelSil, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPersonelDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPersonelDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonelDuzenleActionPerformed
        Personel personel = personelListe.get(personelList.getSelectedIndex());
        PersonelGuncelle personelGuncelle = new PersonelGuncelle(this,personel);
        personelGuncelle.setVisible(true);
    }//GEN-LAST:event_buttonPersonelDuzenleActionPerformed

    private void buttonPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonelEkleActionPerformed
        PersonelEkle personelEkle = new PersonelEkle(this);
        personelEkle.setVisible(true);
    }//GEN-LAST:event_buttonPersonelEkleActionPerformed

    private void buttonPersonelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonelSilActionPerformed
       personelSil();
       listeGuncelle();
    }//GEN-LAST:event_buttonPersonelSilActionPerformed

    private void buttonAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAraActionPerformed
        Musteri musteri = new Musteri();
        personelListe.clear();
        
        personelListe.add(Database.personeliGetir(TFArama.getText()));
        personelList.removeAll();
        
        personelList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return personelListe.size();}
            public String getElementAt(int i) { return personelListe.get(i).toString(); }
        }); 
    }//GEN-LAST:event_buttonAraActionPerformed

    private void buttonCikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCikisYapActionPerformed
        YoneticiIslemleri yoneticiIslemleri = new YoneticiIslemleri(this);
        yoneticiIslemleri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonCikisYapActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFArama;
    private javax.swing.JButton buttonAra;
    private javax.swing.JButton buttonCikisYap;
    private javax.swing.JButton buttonPersonelDuzenle;
    private javax.swing.JButton buttonPersonelEkle;
    private javax.swing.JButton buttonPersonelSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> personelList;
    // End of variables declaration//GEN-END:variables
}
